version: "3.7"
services:
  torrserver:
    image: solopasha/torrserver:latest
    container_name: torrservermatrix
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./db:/torrserver/db
    ports:
      - 8090:8090
    restart: unless-stopped
