#!/usr/bin/with-contenv bash
# shellcheck shell=bash

launch_opts=(
    -d /torrserver/db
    -t /torrserver/db
)
if [[ -n $TS_HTTPAUTH ]]; then launch_opts+=(--httpauth); fi
if [[ -n $TS_RDB ]]; then launch_opts+=(--rdb); fi
if [[ -n $TS_DONTKILL ]]; then launch_opts+=(--dontkill); fi

exec s6-setuidgid abc /usr/bin/torrserver "${launch_opts[@]}"
